---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g phantomjs-prebuilt
  - npm install -g grunt-cli
  - npm install

script:
  - grunt default
